Spree::SubscriptionFrequency.create(title: "weekly", units_count: 1, unit: :weeks)
Spree::SubscriptionFrequency.create(title: "monthly", units_count: 1, unit: :months)
Spree::SubscriptionFrequency.create(title: "quarterly", units_count: 3, unit: :months)
Spree::SubscriptionFrequency.create(title: "half yearly", units_count: 6, unit: :months)
Spree::SubscriptionFrequency.create(title: "yearly", units_count: 12, unit: :months)
