Spree::SubscriptionFrequency.create(title: "every month",    months_count: 1)
Spree::SubscriptionFrequency.create(title: "every 2 months", months_count: 2)
Spree::SubscriptionFrequency.create(title: "every 3 months", months_count: 3)
Spree::SubscriptionFrequency.create(title: "every 4 months", months_count: 4)
Spree::SubscriptionFrequency.create(title: "every 6 months", months_count: 6)
